# Generated by Django 4.0.5 on 2022-11-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/avatar-1.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
