# Generated by Django 4.0.6 on 2022-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_media_post_file_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.TextField(default=''),
        ),
    ]
