# Generated by Django 4.0.5 on 2022-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnails',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
