# Generated by Django 4.0.5 on 2022-09-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'zjc level Documents')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
