# Generated by Django 4.0.5 on 2022-11-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'family and religous studies'), ('2', 'physics'), ('3', 'chemistry'), ('4', 'mathematics'), ('5', 'technology'), ('6', 'english'), ('7', 'shona'), ('8', 'history'), ('9', 'business studies'), ('10', 'biology'), ('11', 'accounts'), ('12', 'combined science'), ('13', 'economics'), ('14', 'geography')], default='1', max_length=8),
        ),
    ]
