# Generated by Django 4.0.5 on 2022-11-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
