# Generated by Django 4.0.5 on 2022-11-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_post_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='audience',
        ),
        migrations.RemoveField(
            model_name='post',
            name='details',
        ),
    ]
