# Generated by Django 4.0.5 on 2022-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_post_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnails',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
